### ISSUE TITLE
Redmine 3.4 compatibility?

### ISSUE THREAD

**Issue by raiblue** [return1/redmine_hide_estimated_hours#15]
Plugin seems broken in Redmine 3.4. 

When I call /issues:
```
[2017-07-18 17:27:52.516 +0300] (31069)  INFO index.html.erb:106:in `block in _plugins_redmine_hide_estimated_hours_app_views_issues_index_html_erb__3632354224006244890_32259320'   Rendered issues/_sidebar.html.erb (12.0ms)
[2017-07-18 17:27:52.519 +0300] (31069)  INFO issues_controller.rb:51:in `block (2 levels) in index'   Rendered plugins/redmine_hide_estimated_hours/app/views/issues/index.html.erb within layouts/base (121.2ms)
[2017-07-18 17:27:52.520 +0300] (31069)  INFO  Completed 500 Internal Server Error in 311ms (ActiveRecord: 94.7ms)
[2017-07-18 17:27:52.522 +0300] (31069) FATAL  
ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    118:                                 :title => l(:label_changes_details)) %>
    119: <% end %>
    120: 
    121: <%= context_menu issues_context_menu_path %>
  app/helpers/application_helper.rb:1300:in `context_menu'
  plugins/redmine_hide_estimated_hours/app/views/issues/index.html.erb:121:in `_plugins_redmine_hide_estimated_hours_app_views_issues_index_html_erb__3632354224006244890_32259320'
  app/controllers/issues_controller.rb:51:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:46:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by return1** [comment]
redmine 3.4 compatibility added
